name: gh-traffic-stats
on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: gh-traffic-stats
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/checkout@v6
        with:
          ref: _gh_traffic_stats
          path: badges-data
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
      - name: Update gh-traffic-stats
        env:
          GH_TOKEN: ${{ secrets.GH_TRAFFIC_TOKEN }}
          REPO: ${{ github.repository }}
          BADGES_DIR: ${{ github.workspace }}/badges-data/.github/badges
          METRICS: clones,views
        run: node .github/update-gh-traffic.mjs
      - name: Commit if changed
        working-directory: badges-data
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .github/badges
          git diff --cached --quiet || (git commit -m "update gh-traffic-stats" && git pull --rebase && git push)
